export interface Puzzle {
  emojis: string;
  answer: string;
  category: string;
  choices: string[];
}

// 55 emoji puzzles
export const PUZZLES: Puzzle[] = [
  { emojis: "🦁👑", answer: "LION KING", category: "Movie", choices: ["LION KING", "KING KONG", "WILD LIFE", "JUNGLE BOOK"] },
  { emojis: "🕷️👨", answer: "SPIDER MAN", category: "Movie", choices: ["SPIDER MAN", "ANT MAN", "BAT MAN", "IRON MAN"] },
  { emojis: "❄️👸", answer: "FROZEN", category: "Movie", choices: ["FROZEN", "TANGLED", "MULAN", "BRAVE"] },
  { emojis: "🦈🌊", answer: "JAWS", category: "Movie", choices: ["JAWS", "TITANIC", "OCEAN", "MOANA"] },
  { emojis: "🚗🏁", answer: "CARS", category: "Movie", choices: ["CARS", "SPEED", "FAST LANE", "DRIVE"] },
  { emojis: "🤖❤️", answer: "WALL E", category: "Movie", choices: ["WALL E", "BIG HERO", "ROBOTS", "TERMINATOR"] },
  { emojis: "🐟🐠", answer: "FINDING NEMO", category: "Movie", choices: ["FINDING NEMO", "SHARK TALE", "AQUAMAN", "LITTLE MERMAID"] },
  { emojis: "🧙👦⚡", answer: "HARRY POTTER", category: "Movie", choices: ["HARRY POTTER", "LORD OF RINGS", "NARNIA", "WIZARD OZ"] },
  { emojis: "🦖🌴", answer: "JURASSIC PARK", category: "Movie", choices: ["JURASSIC PARK", "ICE AGE", "DINO LAND", "KING KONG"] },
  { emojis: "🚢💎🧊", answer: "TITANIC", category: "Movie", choices: ["TITANIC", "POSEIDON", "OCEAN 11", "PIRATES"] },
  { emojis: "👻👻", answer: "GHOSTBUSTERS", category: "Movie", choices: ["GHOSTBUSTERS", "CASPER", "BEETLEJUICE", "HAUNTED"] },
  { emojis: "🌪️👠", answer: "WIZARD OF OZ", category: "Movie", choices: ["WIZARD OF OZ", "TORNADO", "TWISTER", "CINDERELLA"] },
  { emojis: "🐉🐱", answer: "SHREK", category: "Movie", choices: ["SHREK", "PUSS IN BOOTS", "HOW TRAIN DRAGON", "KUNG FU PANDA"] },
  { emojis: "🍫🏭", answer: "CHARLIE CHOCOLATE", category: "Movie", choices: ["CHARLIE CHOCOLATE", "WILLY WONKA", "CANDY LAND", "SWEET LIFE"] },
  { emojis: "🦇👨‍🦱", answer: "BATMAN", category: "Movie", choices: ["BATMAN", "DRACULA", "SUPERMAN", "BLADE"] },
  { emojis: "🍎📱", answer: "APPLE", category: "Brand", choices: ["APPLE", "SAMSUNG", "GOOGLE", "HUAWEI"] },
  { emojis: "🍔👑", answer: "BURGER KING", category: "Brand", choices: ["BURGER KING", "MCDONALDS", "WENDYS", "KFC"] },
  { emojis: "☕🧜‍♀️", answer: "STARBUCKS", category: "Brand", choices: ["STARBUCKS", "COSTA", "DUNKIN", "PEETS"] },
  { emojis: "🏎️🐎", answer: "FERRARI", category: "Brand", choices: ["FERRARI", "PORSCHE", "LAMBO", "MUSTANG"] },
  { emojis: "👟✔️", answer: "NIKE", category: "Brand", choices: ["NIKE", "ADIDAS", "PUMA", "REEBOK"] },
  { emojis: "🐭🏰", answer: "DISNEY", category: "Brand", choices: ["DISNEY", "UNIVERSAL", "PIXAR", "WARNER"] },
  { emojis: "🌮🔔", answer: "TACO BELL", category: "Brand", choices: ["TACO BELL", "CHIPOTLE", "DEL TACO", "QDOBA"] },
  { emojis: "🔴🐂", answer: "RED BULL", category: "Brand", choices: ["RED BULL", "MONSTER", "ROCKSTAR", "POWERADE"] },
  { emojis: "🎸🎤", answer: "ROCK STAR", category: "Phrase", choices: ["ROCK STAR", "POP IDOL", "GUITAR HERO", "BAND"] },
  { emojis: "🌙🚶", answer: "MOONWALK", category: "Phrase", choices: ["MOONWALK", "SKY WALK", "NIGHT WALK", "STAR WALK"] },
  { emojis: "🌊🏄", answer: "SURF WAVE", category: "Phrase", choices: ["SURF WAVE", "OCEAN RIDE", "BEACH FUN", "WAVE RUN"] },
  { emojis: "🔥💪", answer: "STRONG FIRE", category: "Phrase", choices: ["STRONG FIRE", "HOT POWER", "BURN STRONG", "FIRE POWER"] },
  { emojis: "❤️👀", answer: "LOVE AT SIGHT", category: "Phrase", choices: ["LOVE AT SIGHT", "EYE LOVE", "HEART EYE", "SEEING LOVE"] },
  { emojis: "🦶👣", answer: "FOOTSTEPS", category: "Word", choices: ["FOOTSTEPS", "WALKING", "FEET", "TRAIL"] },
  { emojis: "🌈🦄", answer: "MAGIC", category: "Word", choices: ["MAGIC", "FANTASY", "DREAMS", "WONDER"] },
  { emojis: "🌍🌱", answer: "EARTH DAY", category: "Word", choices: ["EARTH DAY", "GREEN", "NATURE", "ECO"] },
  { emojis: "📚🐛", answer: "BOOKWORM", category: "Word", choices: ["BOOKWORM", "READER", "LIBRARY", "STUDY"] },
  { emojis: "🐝🎯", answer: "BEELINE", category: "Word", choices: ["BEELINE", "HONEY", "SWARM", "HIVE"] },
  { emojis: "🦋🐛", answer: "BUTTERFLY", category: "Animal", choices: ["BUTTERFLY", "MOTH", "CATERPILLAR", "INSECT"] },
  { emojis: "🐧❄️", answer: "PENGUIN", category: "Animal", choices: ["PENGUIN", "POLAR BEAR", "SEAL", "ARCTIC FOX"] },
  { emojis: "🐘💨", answer: "ELEPHANT", category: "Animal", choices: ["ELEPHANT", "RHINO", "HIPPO", "MAMMOTH"] },
  { emojis: "🦒🌳", answer: "GIRAFFE", category: "Animal", choices: ["GIRAFFE", "GAZELLE", "OKAPI", "ZEBRA"] },
  { emojis: "🐢🐢", answer: "TURTLE", category: "Animal", choices: ["TURTLE", "TORTOISE", "FROG", "LIZARD"] },
  { emojis: "🍕🇮🇹", answer: "PIZZA", category: "Food", choices: ["PIZZA", "PASTA", "LASAGNA", "RAVIOLI"] },
  { emojis: "🍣🇯🇵", answer: "SUSHI", category: "Food", choices: ["SUSHI", "RAMEN", "TEMPURA", "UDON"] },
  { emojis: "🥐🇫🇷", answer: "CROISSANT", category: "Food", choices: ["CROISSANT", "BAGUETTE", "MACARON", "BRIOCHE"] },
  { emojis: "🌮🇲🇽", answer: "TACO", category: "Food", choices: ["TACO", "BURRITO", "QUESADILLA", "NACHOS"] },
  { emojis: "🍎🥧", answer: "APPLE PIE", category: "Food", choices: ["APPLE PIE", "FRUIT TART", "CRUMBLE", "COBBLER"] },
  { emojis: "🗽🇺🇸", answer: "NEW YORK", category: "Place", choices: ["NEW YORK", "BOSTON", "CHICAGO", "MIAMI"] },
  { emojis: "🗼🇫🇷", answer: "PARIS", category: "Place", choices: ["PARIS", "LYON", "NICE", "MARSEILLE"] },
  { emojis: "🏯🗾", answer: "JAPAN", category: "Place", choices: ["JAPAN", "CHINA", "KOREA", "VIETNAM"] },
  { emojis: "🐨🦘", answer: "AUSTRALIA", category: "Place", choices: ["AUSTRALIA", "NEW ZEALAND", "TASMANIA", "FIJI"] },
  { emojis: "🏛️🏺", answer: "GREECE", category: "Place", choices: ["GREECE", "ROME", "EGYPT", "TURKEY"] },
  { emojis: "⚽🏆", answer: "WORLD CUP", category: "Sport", choices: ["WORLD CUP", "EURO CUP", "CHAMPIONS", "OLYMPICS"] },
  { emojis: "🏀🏆", answer: "NBA FINALS", category: "Sport", choices: ["NBA FINALS", "MARCH MADNESS", "ALL STAR", "DUNK CONTEST"] },
  { emojis: "🎾🏆", answer: "WIMBLEDON", category: "Sport", choices: ["WIMBLEDON", "US OPEN", "FRENCH OPEN", "AUS OPEN"] },
  { emojis: "⛷️⛰️", answer: "SKIING", category: "Sport", choices: ["SKIING", "SNOWBOARD", "HIKING", "CLIMBING"] },
  { emojis: "🏊🥇", answer: "SWIMMING", category: "Sport", choices: ["SWIMMING", "DIVING", "WATER POLO", "SURFING"] },
  { emojis: "🎮🕹️", answer: "VIDEO GAMES", category: "Hobby", choices: ["VIDEO GAMES", "ARCADE", "PINBALL", "CONSOLE"] },
  { emojis: "🎨🖌️", answer: "PAINTING", category: "Hobby", choices: ["PAINTING", "DRAWING", "SKETCH", "ART"] },
  { emojis: "📷📸", answer: "PHOTOGRAPHY", category: "Hobby", choices: ["PHOTOGRAPHY", "CAMERA", "PICTURES", "SHOOTING"] },
];
